name: Build package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - fusebox
        arch:
          - x86_64
          - aarch64
        version:
          - tau1
    runs-on: ${{ matrix.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
    container:
      image: registry.fedoraproject.org/fedora:39
      options: --cap-add=SYS_ADMIN --privileged

    steps:
      - name: Install repositories and dependencies
        run: |
          dnf install -y dnf-plugins-core
          dnf config-manager --add-repo https://github.com/terrapkg/subatomic-repos/raw/main/tau1.repo
          dnf install -y anda mock subatomic-cli tau-mock-configs git curl wget

      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          set-safe-directory: true

      - run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: andaman-common-pkgs/anda-build@main
        with:
          name: ${{ matrix.pkg }}
          mockConfig: tau-1-${{ matrix.arch }}
          andaRepo: https://github.com/terrapkg/subatomic-repos/raw/main/terra39.repo

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.pkg }}-${{ matrix.arch }}-${{ matrix.version }}
          path: anda-build/rpm/rpms/*

      - name: Upload to subatomic
        if: github.event_name != 'pull_request'
        run: |
          subatomic-cli upload --prune \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            ${{ matrix.version }} anda-build/rpm/rpms/*
